-
  version: 1.0.{build}
  image: Visual Studio 2017
  clone_depth: 1
  branches:
    except:
      - master
  install:
  - set PATH=C:\Ruby25\bin;%PATH%
  - gem install bundler --no-ri --no-rdoc
  - bundle install
  build_script:
  - bundle exec rake
  test: off
  artifacts:
  - path: build\pkg\DotNetZip.*.nupkg
    name: Nuget Package
-
  version: 1.0.{build}
  image: Visual Studio 2017
  clone_depth: 1
  branches:
    only:
      - master
  install:
  - set PATH=C:\Ruby25\bin;%PATH%
  - gem install bundler --no-ri --no-rdoc
  - bundle install
  build_script:
  - bundle exec rake
  test: off
  artifacts:
  - path: build\pkg\*.nupkg
    name: Nuget Package
  - path: '**\*.nuspec'
  deploy:
  - provider: NuGet
    api_key:
      secure: M7LFZYxeE65s2U7APTgVFyzBDEiE5LFVFIf+d3ahGxgylxrctFcFJx9cmnamH30f
    skip_symbols: true
    artifact: /.*\.nupkg/ 
